import { Advent_Pro } from "next/font/google";
import "./globals.css";

const adventPro = Advent_Pro({
  weight: "variable",
  subsets: ["latin"],
  variable: "--font-advent-pro",
  display: "swap",
});

export const metadata = {
  title: "Motivational Lifestyle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${adventPro.variable} h-full antialiased`}
    >
      <body className="h-full overflow-hidden font-sans">{children}</body>
    </html>
  );
}
